### ISSUE TITLE
UncaughtThrowError: on next/continue

### ISSUE THREAD

**Issue by khanchi97** [meinac/pry-shell#3]
I put the breakpoint using `binding.pry_shell` and when I try to move the execution forward with `next` or `continue` I get the following error:

 (Note: I don't face this problem when using the `with_byebug` option which is experimental I guess)

```
[1] pry(#<Projects::CreateService>)> next
UncaughtThrowError: uncaught throw :breakout_nav
from /home/khanchi/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/gitlab-pry-byebug-3.9.0/lib/pry-byebug/helpers/navigation.rb:15:in `throw'
```
Now I can't do anything, but exit the `pry_shell` process with a SIGTERM.

**Comment by meinac** [comment]
Thanks for the report @khanchi97. I will remove the need of using `with_byebug` option to enable byebug which will fix this problem.

**Comment by khanchi97** [comment]
> Thanks for the report @khanchi97. I will remove the need of using `with_byebug` option to enable byebug which will fix this problem.

Does it mean now `byebug` will the default?

**Comment by meinac** [comment]
> > Thanks for the report @khanchi97. I will remove the need of using `with_byebug` option to enable byebug which will fix this problem.
> 
> Does it mean now `byebug` will be the default?

Yes.

**Comment by khanchi97** [comment]
Okay, thanks. Thanks for the tool also :)

I wonder how people until this tool used to debug with `binding` for background jobs.

**Comment by meinac** [comment]
@khanchi97 - I've released a new version of the Gem. Could you please try the version `0.5.0` and let me know if the issue has been fixed.

**Comment by khanchi97** [comment]
@meinac yes, I just checked with version `0.5.0` the error has been fixed. I guess the issue can be closed now. Thanks :)
