### ISSUE TITLE
Key mapping on Main Menu for easy navigation

### ISSUE THREAD

**Issue by khanchi97** [meinac/pry-shell#4]
Is it possible to add `j(down),k(up)` to navigate options available at Main Menu prompt?

**Comment by meinac** [comment]
@khanchi97 - I don't know if we can assign more than one key for an action with the underlying library called `tty-prompt`. If so, we can do it.

If it's not possible, probably we need to introduce `pry-shell.profile`(similar to `bash-profile`) which can be edited by users to configure `pry-shell` the way they want.

Either case, I am a little bit busy at the moment so probably I won't be able to pick this up soon, however, any contribution is more than welcome on this :)

**Comment by khanchi97** [comment]
Turned out that `tty-prompt` has support to add key bindings :tada: 

I've created an MR, please check out #5
